
spring:
  application:
    name: eureka-provider

server:
  port: 8002

eureka:
  # 配置开启健康检查
  client:
    healthcheck:
      enabled: true
    service-url:
      # 向每个注册中心注册
      defaultZone: http://192.168.10.131:8762/eureka/