
spring:
  application:
    name: eureka-consumer-feign

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

# Feign是自带断路器的，在D版本的Spring Cloud中，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码：
feign:
  hystrix:
    enabled: true    #打开 Feign 的熔断功能
