
spring:
  application:
    name: eureka-consumer-ribbon

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.131:8762/eureka/

# Ribbon 的负载均衡策略 随机策略， 轮询策略：RoundRobinRule
eureka-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule