spring:
  application:
    name: eureka-zuul

server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://192.168.10.131:8762/eureka/

zuul:
  routes:
    #api-a:
      #path: /api-a/**
      #serviceId: eureka-consumer-feign
    #简洁写法
    eureka-consumer-feign: /api-a/**
    api-b:
      path: /api-b/**
      serviceId: eureka-consumer-ribbon

logging:
  config: